### ISSUE TITLE
`RichText.Definitions.link` bad `htmlToNode`

### ISSUE THREAD

**Issue by tgelu** [mweiss/elm-rte-toolkit#27]
In the Definition of `link`, the `htmlToNode` function seems to confuse `href` with `src` in [here](https://github.com/mweiss/elm-rte-toolkit/blob/master/src/RichText/Definitions.elm#L539).
This has the consequence that pasting (or parsing html with a link) won't work because the link has an `href` not an `src`.

Am I missing something?

**Comment by mweiss** [comment]
That definitely looks like a bug!

**Comment by rjdellecese** [comment]
Is the fix simply to replace `"src"` with `"href"` in that line you referenced @tgelu? If so, would you like to open a PR? If not, I would be happy to!

**Comment by mweiss** [comment]
Yeah it’s exactly that!  Sorry I’ve been busy with other projects recently.  If you can open a PR I’ll merge it in.  Thanks!!

**Comment by mweiss** [comment]
Thank you so much @tgelu for reporting this and @rjdellecese for the fix!  This has been published in 1.0.3
