### ISSUE TITLE
ranges are persisted after deselection

### ISSUE THREAD

**Issue by BrianHicks** [mweiss/elm-rte-toolkit#9]
in the demo on https://mweiss.github.io/elm-rte-toolkit/, I noticed that if you:

1. select some text
2. click outside the editor (inc. the toolbar)
3. click a formatting button in the toolbar

then the range you selected will be restored and the format will be applied. I expected it to stay deselected.

edit: in case it matters, I'm using Safari 13.0.5

**Comment by mweiss** [comment]
Thanks for reporting this!  I believe I fixed the issue (luckily, only the javascript and the demo code had to be updated).  I've upload the fix to the demo page, let me know if it's still occuring.

**Comment by BrianHicks** [comment]
looks great, thank you!
